# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    # Test name: Login
    # Step # | name | target | value
    # 1 | open | http://localhost:8080/pages/login | 
    self.driver.get("http://localhost:8080/pages/login")
    # 2 | type | xpath=//*[@data-test-id="usernameInput"] | admin@niagaku.com
    self.driver.find_element(By.XPATH, "//*[@data-test-id=\"usernameInput\"]").send_keys("admin@niagaku.com")
    # 3 | type | xpath=//*[@data-test-id="passwordInput"] | qwe123
    self.driver.find_element(By.XPATH, "//*[@data-test-id=\"passwordInput\"]").send_keys("qwe123")
    # 4 | click | css=.btn-success | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 5 | close |  | 
    self.driver.close()
  
